site_name: Docker Container ASDF
repo_url: https://github.com/jrosco/docker-container-asdf
repo_name: docker-container-asdf
docs_dir: docs/
nav:
  - Home: index.md
  - Toolsets:
    - Overview: toolsets/README.md
    - Helm: toolsets/helm/README.md
    - AWS CLI: toolsets/awscli/README.md
    - Terraform: toolsets/terraform/README.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
