# https://docs.docker.com/compose/compose-file/build/
services:
  alpine:
    image: ${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        asdf_image: "${ALPINE_IMAGE_REPO_PATH}"
        packages: ${TERRAFORM_PACKAGES}
      platforms:
        - "linux/amd64"
      tags:
        # main
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:latest" # set alpine as default latest images
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:${ASDF_VERSION}" # set alpine as default asdf image
        # alpine x.x.x
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_VERSION}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_VERSION}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_VERSION}-${ASDF_VERSION}-build${BUILD_NUMBER}"
        # alpine x.x
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_MAJOR_VERSION}.${ALPINE_MINOR_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_MAJOR_VERSION}.${ALPINE_MINOR_VERSION}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_MAJOR_VERSION}.${ALPINE_MINOR_VERSION}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine-${ALPINE_MAJOR_VERSION}.${ALPINE_MINOR_VERSION}-${ASDF_VERSION}-build${BUILD_NUMBER}"
        # alpine major
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine${ALPINE_MAJOR_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine${ALPINE_MAJOR_VERSION}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine${ALPINE_MAJOR_VERSION}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:alpine${ALPINE_MAJOR_VERSION}-${ASDF_VERSION}-build${BUILD_NUMBER}"

      labels:
        - "asdf-version=${ASDF_VERSION}"

  debian:
    image: ${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian
    build:
      context: .
      dockerfile: Dockerfile
      args:
        asdf_image: "${DEBIAN_IMAGE_REPO_PATH}"
        packages: ${TERRAFORM_PACKAGES}
      platforms:
        - "linux/amd64"
      tags:
        # main
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${ASDF_VERSION}-build${BUILD_NUMBER}"
        # debian x.x
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION}-${ASDF_VERSION}-build${BUILD_NUMBER}"
        # debian major
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian${DEBIAN_MAJOR_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian${DEBIAN_MAJOR_VERSION}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian${DEBIAN_MAJOR_VERSION}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian${DEBIAN_MAJOR_VERSION}-${ASDF_VERSION}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian${DEBIAN_MAJOR_VERSION}-${DEBIAN_VERSION_CODENAME}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian${DEBIAN_MAJOR_VERSION}-${DEBIAN_VERSION_CODENAME}-${ASDF_VERSION}-build${BUILD_NUMBER}"
        # debian codename
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION_CODENAME}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION_CODENAME}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION_CODENAME}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION_CODENAME}-${ASDF_VERSION}-build${BUILD_NUMBER}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION_CODENAME}-${DEBIAN_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION_CODENAME}-${DEBIAN_VERSION}-${ASDF_VERSION}"
        - "${ASDF_REGISTRY_TOOLSET}/terraform-toolset:debian-${DEBIAN_VERSION_CODENAME}-${DEBIAN_VERSION}-${ASDF_VERSION}-build${BUILD_NUMBER}"

      labels:
        - "asdf-version=${ASDF_VERSION}"

  # disabled redhat as it does not support golang 1.24.4 required for asdf
  # when ready to enable see
  # https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?gs&q=go%20tool
  # redhat:
  #   image: ${ASDF_REGISTRY_TOOLSET}/terraform:redhat
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       image: "${REDHAT_IMAGE_REPO_PATH}:latest"
  #       packages: ${HELM_PACKAGES}
  #       asdf_version: ${ASDF_VERSION}
  #     platforms:
  #       - "linux/amd64"
  #     tags:
  #       - ${ASDF_REGISTRY_TOOLSET}/terraform:redhat-${GIT_TAG}
  #       - ${ASDF_REGISTRY_TOOLSET}/terraform:${ASDF_VERSION}-redhat-${REDHAT_VERSION}
  #       - ${ASDF_REGISTRY_TOOLSET}/terraform:${ASDF_MAJOR_VERSION}-redhat-${REDHAT_MAJOR_VERSION}
  #       - ${ASDF_REGISTRY_TOOLSET}/terraform:${ASDF_MAJOR_VERSION}.${ASDF_MINOR_VERSION}-redhat-${REDHAT_MAJOR_VERSION}.${REDHAT_MINOR_VERSION}
  #       - ${ASDF_REGISTRY_TOOLSET}/terraform:${ASDF_VERSION_SHORTHAND}-${REDHAT_VERSION_SHORTHAND}
  #
  #     labels:
  #       - "asdf-version=${ASDF_VERSION}"
