# https://docs.docker.com/compose/compose-file/build/
services:
  alpine:
    image: ${ASDF_REGISTRY_TOOLSET}/awscli:alpine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: "${ALPINE_IMAGE_REPO_PATH}:latest"
        packages: ${AWSCLI_PACKAGES}
        asdf_version: ${ASDF_VERSION}
      platforms:
        - "linux/amd64"
      tags:
        - ${ASDF_REGISTRY_TOOLSET}/awscli:alpine-${GIT_TAG}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_VERSION}-alpine-${ALPINE_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_MAJOR_VERSION}-alpine-${ALPINE_MAJOR_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_MAJOR_VERSION}.${ASDF_MINOR_VERSION}-alpine-${ALPINE_MAJOR_VERSION}.${ALPINE_MINOR_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_VERSION_SHORTHAND}-${ALPINE_VERSION_SHORTHAND}

      labels:
        - "asdf-version=${ASDF_VERSION}"

  ubuntu:
    image: ${ASDF_REGISTRY_TOOLSET}/awscli:ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: "${UBUNTU_IMAGE_REPO_PATH}:latest"
        packages: ${AWSCLI_PACKAGES}
        asdf_version: ${ASDF_VERSION}
      platforms:
        - "linux/amd64"
      tags:
        - ${ASDF_REGISTRY_TOOLSET}/awscli:ubuntu-${GIT_TAG}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_VERSION}-ubuntu-${UBUNTU_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_MAJOR_VERSION}-ubuntu-${UBUNTU_MAJOR_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_MAJOR_VERSION}.${ASDF_MINOR_VERSION}-ubuntu-${UBUNTU_MAJOR_VERSION}.${UBUNTU_MINOR_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_VERSION_SHORTHAND}-${UBUNTU_VERSION_SHORTHAND}

      labels:
        - "asdf-version=${ASDF_VERSION}"
  
  redhat:
    image: ${ASDF_REGISTRY_TOOLSET}/awscli:redhat
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: "${REDHAT_IMAGE_REPO_PATH}:latest"
        packages: ${AWSCLI_PACKAGES}
        asdf_version: ${ASDF_VERSION}
      platforms:
        - "linux/amd64"
      tags:
        - ${ASDF_REGISTRY_TOOLSET}/awscli:redhat-${GIT_TAG}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_VERSION}-redhat-${REDHAT_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_MAJOR_VERSION}-redhat-${REDHAT_MAJOR_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_MAJOR_VERSION}.${ASDF_MINOR_VERSION}-redhat-${REDHAT_MAJOR_VERSION}.${REDHAT_MINOR_VERSION}
        - ${ASDF_REGISTRY_TOOLSET}/awscli:${ASDF_VERSION_SHORTHAND}-${REDHAT_VERSION_SHORTHAND}

      labels:
        - "asdf-version=${ASDF_VERSION}"