name: Docker Compose Action [merge]
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.gitignore'
      - '.github/**'

jobs:
  tag-semver-release:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.semver.outputs.tag }} # Capture the output
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        # docs: https://github.com/anothrNick/github-tag-action
        # Any commit message that includes #major, #minor, #patch, or #none will trigger the respective version bump.
        # If no #major, #minor or #patch tag is contained in the merge commit message, it will bump whichever DEFAULT_BUMP
        # is set to (which is minor by default) 
        uses: anothrNick/github-tag-action@v1
        id: semver # Keep the ID for the step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          PRERELEASE: false
          DEFAULT_BUMP: minor

  build-and-push:
    runs-on: ubuntu-latest
    needs: tag-semver-release # Make sure this job runs after tag-semver-release
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build images and tags
        run: |
          BUILD_NUMBER=${{ needs.tag-semver-release.outputs.tag }} \
          docker \
            compose build
      - name: Docker lists builds
        run: docker images
      - name: Docker push-image
        run: |
          retry() {
            for i in {1..5}; do
              BUILD_NUMBER=${{ needs.tag-semver-release.outputs.tag }} \
              docker \
                compose push && break || sleep 10
            done
          }
          retry
