name: Check Alpine Version Updates [bot_task]

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for branch checks

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python .github/scripts/update_dep_version.py alpine

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feature/dependencies-version-check/update-alpine-to-latest
          base: main
          commit-message: "chore(deps): :arrow_up: update Alpine to latest version #none"
          title: ":arrow_up: [alpine] Automated dependency update"
          body: |
            This is an automated update PR created by our dependency update bot. It scans for new releases of Alpine and updates the version accordingly.

            🔄 Changes in this PR:
              * Updated `ALPINE_VERSION` to the latest release.
              * Adjusted `ALPINE_MAJOR_VERSION`, `ALPINE_MINOR_VERSION`, and `ALPINE_PATCH_VERSION` based on the new version.

            🛠 How this works:
              * The bot runs on a scheduled workflow to check for new Alpine releases.
              * If a new version is found, it updates the configuration file and creates this PR.
              * This ensures we always stay up to date with the latest improvements and security patches.

            📌 Next Steps:
              * Review the changes.
              * Merge if everything looks good! ✅

            Releases details: [alpine releases](https://alpinelinux.org/releases/)

            - [ ] Open this PR for review to trigger other workflows [see limitations](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs)

            ⚡ This PR was auto-generated by our dependency update workflow. 🚀
          labels: |
            dependencies
            automated
          delete-branch: false
          draft: true # allows PR to run other workflows when "Ready for review"
